### PR TITLE
Update LcpK0s database for ML model and introduce data periods selection

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
implemented by @DelloStritto

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@ginnocen @DelloStritto 
I thought we put it on top of that so we have all the most recent databases in one place after merging this PR. Do you agree?
Hence, we might close https://github.com/ginnocen/MachineLearningHEP/pull/591

**Comment by DelloStritto** [comment]
Yes, I agree. 
Go on. 


Da: "benedikt-voelkel" <notifications@github.com> 
A: "ginnocen/MachineLearningHEP" <MachineLearningHEP@noreply.github.com> 
Cc: "DelloStritto" <luigi.dellostritto@sa.infn.it>, "Mention" <mention@noreply.github.com> 
Inviato: Mercoledì, 18 marzo 2020 13:18:22 
Oggetto: Re: [ginnocen/MachineLearningHEP] Update LcpK0s database for ML model (#592) 





[ https://github.com/ginnocen | @ginnocen ] [ https://github.com/DelloStritto | @DelloStritto ] 
I thought we put it on top of that so we have all the most recent databases in one place after merging this PR. Do you agree? 
Hence, we might close [ https://github.com/ginnocen/MachineLearningHEP/pull/591 | #591 ]

**Comment by benedikt-voelkel** [comment]
Ciao @ginnocen 
I put now another Commit on top which allows one to choose the data periods to be used explicitly. I checked that
1) the results are the same (all fitted values are 1:1 the same, corrected yield as well) if I don't specify any periods **or** if I request all periods
2) of course, results change slightly if I request only some periods

This allows us, for instance, to take only the 2016 periods which can be used for V0M as discussed in the D2H meeting

**Comment by ginnocen** [comment]
Hi @benedikt-voelkel @DelloStritto. As discussed offline, I would suggest that we use this setup only in the validation stage. In this way, we would avoid that people in the future inherit an obsolete period by period run selection used for computing the central values. I will now reintroduce a skeleton of the validation stage, where we can insert this (very useful) development. Let me know if it works for all of you.

**Comment by benedikt-voelkel** [comment]
Hej @ginnocen 
I think we can close this. The only thing we might want to keep is the change in `utilities.py` as this should speed-up quite a bit. In the old one it was looping the dataframe basically row by row

**Pull request closed without merging**
