### PR TITLE
Add max chi2 and min signif for ML syst

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
This is just a small PR, however, introducing minimal significance and maximum red. chi2 for ML systematic fits so it's centrally available in the database now

### CODE REVIEW

**Comment by ginnocen** [comment]
@benedikt-voelkel shouldn't we read it somewhere?

**Comment by benedikt-voelkel** [comment]
@ginnocen  That's already there: https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/analysis/systematics.py#L222-L223

**Comment by benedikt-voelkel** [comment]
The DB changes might have slipped through at some point

**Comment by ginnocen** [comment]
thanks. I missed that.

**Pull request merged**
