### PR TITLE
Add mult analysis in D0 DBs

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Ciao @ginnocen 
I created another DB for D0 in case of multiplicity analyses. This was done because as you can see in the current one we have a couple of these things: https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_zg_0304.yml#L254

This is not on analysis level but before and I don't know if more of these things will be introduced for jet analyses so I thought it might make sense to just introduce a dedicated D0 DB for mult. analyses

**Comment by ginnocen** [comment]
Hi @benedikt-voelkel @vkucera are you sure you want to split the two DB? I would consider using exactly the same setup as Vit if possible. For the D0 zg we didn't use machine learning given that the signal are pretty good already. By using the same data/setup also for the D0 vs multiplicity analysis we would implicitly validate also the zg one. Unless you see specific reasons for doing it of course 😄

**Comment by benedikt-voelkel** [comment]
Hej @ginnocen 
I splitted the DBs because of my first comment above. At some point it crashes because it tries to read the field `probcutoptimal` (seems it doesn't matter at this point whether we are doing STD or ML analysis with the package): https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_zg_0304.yml#L254. It crashes because it gets a string and not a list as expected.
But we can prevent the things from reading it in case we are not doing ML analysis. Should I add such a protection in the corresponding places? Then, we don't need to split. 

What do you think?

**Comment by ginnocen** [comment]
@benedikt-voelkel. It sounds good to me to make it such that he doesn't read it if it is not ML.

**Comment by benedikt-voelkel** [comment]
@ginnocen Ok, give me 15 mins

**Comment by benedikt-voelkel** [comment]
@ginnocen That works for me
I had to do this: https://github.com/ginnocen/MachineLearningHEP/pull/593/files#diff-e2f6c44ae43844bbf4fc0ee16992170dR148-R151
So there have to be values in these lists even if no ML analysis is done. This is because those values are used for building histogram and file names. If we wanted to change that, a few more changes would be necessary in the code

**Comment by benedikt-voelkel** [comment]
Hej @ginnocen This is the ntrkl analysis, so nothing jet related. Did/do you work with that @vkucera ?
In any case, these sigma values are close to the final fit values. You can all check if you want. In fact, the last pT bin of the init list was 0.1 before, but the sigma was fitted to something well `~0.15`. Since we define a fit as failed when its sigma deviates more than a relative fraction from the init value, the fit is marked as failed although it looked very nice.
(heres is the relative fraction the sigma is allowed to deviate: https://github.com/ginnocen/MachineLearningHEP/pull/593/files#diff-ff885d230a147daf298133c92b6006fcR541)

**Comment by ginnocen** [comment]
@benedikt-voelkel you are right. Good to be merged for me.

**Pull request merged**
