### PR TITLE
Add Bayesian model optimisation via hyperopt

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
* set search space in template_<model>.py

* construct class deriving from BayesianOpt in template_<model>.py

* add function <full_model_name>_bayesian_opt(central_model_params) in
  template_<model>.py

Examples can be found in template_xgboost.py

Bayesian model optimisation is enabled in the run configuration YAML
setting the option dobayesianopt = true

Co-developed with @harisriaz17

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Ciao @ginnocen  and @harisriaz17
I have put everything together for a Bayesian model optimisation using `hyperopt` as suggested by @harisriaz17

The only thing one needs to do now is to take the new implementation in `template_xgboost.py` as an example to implement this very easily for other models as well. This requires only a very few lines as one can see.

Everything else is handled internally in `optimisation/bayesian_opt.py`'s `BayesianOpt`. All trials as well as the best model is saved, hence it can be used immediately for application.

Multiple scoring metrics can be defined, one of that has to be chosen to be the one which is optimised. These metrics are written to disc as well together with the index of the best configuration.

What do you think?

**Comment by benedikt-voelkel** [comment]
Ciao @ginnocen 
From my side we can merge this PR

**Comment by ginnocen** [comment]
Hi @benedikt-voelkel! Ok perfect! I am trying it now :).

**Comment by benedikt-voelkel** [comment]
@ginnocen There is a `Keras` and `XGBoost` implementation
They can be find in their respective `templates_<model>.py`

**Pull request merged**
