### PR TITLE
Read invmass and y values from database + configurable acc selection

### PR DESCRIPTION
**Pull request by ginnocen**

### CODE REVIEW

**Comment by ginnocen** [comment]
@LuukVermunt can you check this doesnt create conflicts with multiplicity dependent analysis? 
It will of course require to add a few entries in the databases of other analyses. Thanks!

**Comment by lvermunt** [comment]
Hi @ginnocen, 
Looks ok to me, but I would make it backwards compatible so we don't have to change 20+ databases. You can do like:
```
self.s_apply_yptacccut = datap.get("apply_yptacccut", True)
self.v_invmass = datap["variables"].get("var_inv_mass", "inv_mass")
self.v_rapy = datap["variables"],get("var_y", "y_cand")
self.s_var_evt_sel = datap["variables"].get("var_evt_sel", "is_ev_rej")
``` 
at the various locations (processer.py and processerdhadrons.py)

**Comment by ginnocen** [comment]
hi @LuukVermunt, yeah that's a good idea. Cheers GM

**Comment by ginnocen** [comment]
@njacazio. I added the scenario2/3 databases. Please have a look. GM

**Pull request merged**
