### PR TITLE
WIP: Modification to run on a single pt bin + few extra fixes

### PR DESCRIPTION
**Pull request by ginnocen**
@jaimenorman Please find in this PR the modifications needed to run on a single pt bin (8-12 GeV). I made a few tests and indeed we need to make some extra selections to reduce the size that is too big. I added few notes in the database but all seems to work fine.

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Hello
@ginnocen @jaimenorman 
I have opened #652 which allows you to provide a snippet of the nominal database, say call it `overwrite.yaml`
To cover this PR with that you would create an `overwrite.yaml`

```yaml
sel_reco_skim: ["pt_prong0>0.40 and pt_prong1>0.40 and pt_prong2>0.40"] #sel_skim_binmin bins
sel_gen_skim: [null] #sel_skim_binmin bins
sel_skim_binmin: [8] #list of nbins
sel_skim_binmax: [12] #list of nbins

multi:
  data:
    fracmerge : [0.05,0.05] #list of periods
ml:
  binmin: [8] #list of nbins sel_skim_binmin bins
  binmax: [12] #list of nbins sel_skim_binmin bins

mlapplication:
  data:
    # and so forth
```

The good thing is you can use this then for any future test of nominal databases and don't need to change databases over and over again. Just run

```bash
python do_entire_anaysis.py -r <default_complete> -d <nominal_db> --database-overwrite overwrite.yaml
```

What do you think?

**Comment by ginnocen** [comment]
hi @jaimenorman please let us know if Benedikt's PR is ok for you. In that case, I close this PR

**Comment by jaimenorman** [comment]
Hi @ginnocen , @benedikt-voelkel ,
Thanks a lot, this looks useful!

**Comment by benedikt-voelkel** [comment]
@jaimenorman 
just let me know if you need further instructions besides the longer comment I made above. Otherwise, tell me if it works for you and then we can close this one :)

**Comment by benedikt-voelkel** [comment]
Hej @jaimenorman @ginnocen 
When you have time, let me know if this PR is still needed. Otherwise, I will close it :)

**Pull request closed without merging**
