### PR TITLE
Some development for XGBoost

### PR DESCRIPTION
**Pull request by fcatalan92**

### CODE REVIEW

**Comment by fcatalan92** [comment]
Hi Gian Michele,

> thanks for the PR. I was just wondering if we can find a way to preserve backward compatibility.
> E.g. we could add some versioning of the model available in the configuration file. One possibility is to add an underscore like xgboost_v0_sqmLc for the old one and some different description (up to you) for the new one.

If you are referring to the compatibility with the SQM analyses I think that we could use the `version0_sqm` branch for that. In this way we can also guarantee the same version of the software and libraries (I think that keeping the pace with the development of the ML libraries is important but this could break the reproducibility). What do you think?

>We would have to fix function in the template to get the parameters only if available in config_model_parameters.yml, so that he doesn't crash in case it doesn't find the parameters specified. This is just one possibility, any better solution is very welcome.

In my opinion the easiest way to do that is to keep in the function template all the possible parameters that we could want to tune (in this PR I added a few but we could also decide to have all of the ones available) and set in `config_model_parameters.yml` their value to the default one. So the final effect is the same as to not have them and different configurations could be added and managed with the `activated` flag.

**Comment by ginnocen** [comment]
Hi Fabio, 
I think it is still preferable to have the option of running the old models also in the new version of the software framework. Also cause it is not given that the new parameters are the best one for all analyses. We might at some point to have different configuration for pp and PbPb for example. I think a way to have multiple model configuration should be foreseen. Don't you think? 
Cheers GM

**Comment by fcatalan92** [comment]
Hi Gian Michele,
I completely agree with you and indeed what I propose allows to do this. With the current state of this PR you can have a `config_model_parameters.yml` like this:

```
xgboost:
  xgboost_classifier_newconf:
     activate: True
     old_par: custom value
     old_par: custom value
     new_par: custom value
     new_par: custom value
  xgboost_classifier_oldconf:
     activate: False
     old_par: custom value
     old_par: custom value
     new_par: default value
     new_par: default value
```
where the `default value` is taken from the [default configuration](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBClassifier) of the model. In this way you can run also the old model configurations (the "trick" is to assign explicitly the default value to the parameters). Moreover you can add different configurations for different collision systems, analyses, etc.

**Comment by fcatalan92** [comment]
Hi @ginnocen, if the solution I proposed in the last comment is fine for you this PR is ready to be merged.

**Pull request merged**
